### ISSUE TITLE
Practica de costos 

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-3-practica-de-costos-promastergamer777#1]
Practica 3

**Comment by FedericoVictorianoSierra** [comment]
[Practica de Costos (Federico Victoriano Sierra).pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-costos-promastergamer777/files/10827177/Practica.de.Costos.Federico.Victoriano.Sierra.pdf)

**Comment by Heidi-19** [comment]
[Practica 2 (3).pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-costos-promastergamer777/files/10829840/Practica.2.3.pdf)

**Comment by SANDRAVELASCO** [comment]
[Practica Sandra Gabriela Velasco Guzmán.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-costos-promastergamer777/files/10829870/Practica.Sandra.Gabriela.Velasco.Guzman.pdf)

**Comment by JoseABCruz** [comment]
[Practica 2 (José Antonio Balbuena Cruz).pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-costos-promastergamer777/files/10830230/Practica.2.Jose.Antonio.Balbuena.Cruz.pdf)

**Comment by mel-16** [comment]
20% MUY BIEN

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
